apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: test
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: test