apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: namespace-workflow-1766924689148
  labels:
    app.kubernetes.io/name: test
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80