# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - contacts-api-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: |
            ${{ github.workspace }}/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: './app'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E2C6F578BCB34C07861EC72F905C34B5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_674E9FA98B5C474D8688FC42C2B0E053 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_12257B6D9F5044D4961FFE30C9169C0A }}

      - name: Configure App Service Settings
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az webapp config appsettings set --resource-group rgonzalez-group-demo --name contacts-api-demo \
              --settings \
              SPRING_PROFILES_ACTIVE="mix2" \
              SPRING_DATASOURCE_URL="jdbc:postgresql://rgonzalez-db-interview.postgres.database.azure.com:5432/smbc_data" \
              SPRING_DATASOURCE_USERNAME="rgonzalez_admin" \
              SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              SPRING_DATASOURCE_SECONDARY_URL="jdbc:postgresql://rgonzalez-db-interview.postgres.database.azure.com:5432/smbc_data" \
              SPRING_DATASOURCE_SECONDARY_USERNAME="rgonzalez_admin" \
              SPRING_DATASOURCE_SECONDARY_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              SPRING_KAFKA_BOOTSTRAP_SERVERS="rgonzalez-messaging-interview.servicebus.windows.net:9093" \
              SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS="rgonzalez-messaging-interview.servicebus.windows.net:9093" \
              SPRING_KAFKA_ADMIN_PROPERTIES_BOOTSTRAP_SERVERS="rgonzalez-messaging-interview.servicebus.windows.net:9093" \
              SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG="${{ secrets.KAFKA_SASL_CONFIG }}"
            
            az webapp config set --resource-group rgonzalez-group-demo --name contacts-api-demo \
              --startup-file "java -Dspring.profiles.active=default,mix2 -jar /home/site/wwwroot/contacts-api-0.0.2-SNAPSHOT.jar"

      # - name: Clear wwwroot folder
      #   uses: azure/CLI@v2
      #   with:
      #     inlineScript: |
      #       az webapp deployment slot config --resource-group rgonzalez-group-demo --name contacts-api-demo --slot Production --auto-swap true
      #       az webapp up --resource-group rgonzalez-group-demo --name contacts-api-demo --os-type Linux || true

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'contacts-api-demo'
          slot-name: 'Production'
          package: './app'

      # - name: Health Check
      #   run: |
      #     max_attempts=30
      #     attempt=0
      #     while [ $attempt -lt $max_attempts ]; do
      #       response=$(curl -s -o /dev/null -w "%{http_code}" https://contacts-api-demo-h8cgeuapd7gcd4d4.eastus-01.azurewebsites.net/actuator/health)
      #       if [ $response -eq 200 ]; then
      #         echo "Health check passed! Application is running."
      #         exit 0
      #       fi
      #       echo "Attempt $((attempt + 1))/$max_attempts - Status: $response"
      #       sleep 2
      #       attempt=$((attempt + 1))
      #     done
      #     echo "Health check failed after $max_attempts attempts"
      #     exit 1
          